---
title: "Schelling's Segregation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Schelling's Segregation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyabm)
```

```{r segregation}
agent_a <- create_agent() %>% 
  set_characteristic(color = 'red') %>% 
  add_variable(similar = \(me, abm) {
    neighbors <- grid_get_neighbors(me, abm, which = 'o')
    return(sum(neighbors$color == me$color)/nrow(neighbors))
  }) %>% 
  add_variable(unhappy = \(me, abm) {
    return(me$similar < .15)
  }) %>% 
  add_rule('move',
           \(me, abm) {
             spot <- grid_get_free_neighboring_spots(me, abm, which = 'o') %>% 
               dplyr::slice_sample(n = 1)
             grid_move(me, abm, 
                       new_x = spot$.x,
                       new_y = spot$.y) %>% 
               return()
           },
           unhappy == TRUE)

agent_b <- agent_a %>% 
  set_characteristic(color = 'blue',
                     .overwrite = TRUE)

model <- create_grid_environment(seed = 5381,
                                 size = 40) %>% 
  add_agents(agent_a,
             n = 40*40*0.4) %>% 
  add_agents(agent_b,
             n = 40*40*0.4) %>% 
  add_variable(mean_similar = \(me, abm) {
    abm %>% 
      convert_agents_to_tibble() %>% 
      tidycomm::describe(similar) %>% 
      dplyr::pull(M) %>% 
      return()
  }) %>% 
  add_variable(share_unhappy = \(me, abm) {
    abm %>% 
      convert_agents_to_tibble() %>% 
      dplyr::summarise(share_unhappy = sum(unhappy)/dplyr::n()) %>% 
      dplyr::pull(share_unhappy) %>% 
      return()
  }) %>% 
  add_rule(stop_abm,
           share_unhappy <= 0) %>% 
  init() %>% 
  iterate()
```
